INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (1, 1, 'ค่าพิจารณาคำขอรับเลขสถานที่ผลิตอาหารที่ไม่เข้าข่ายโรงงาน (แบบ สบ.1) [ตามบัญชีข้อ 1.1(1)]', '1000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (2, 1, 'ค่าพิจารณาการยื่นแบบการแก้ไขสถานที่ผลิตอาหารที่ไม่เข้าข่ายโรงงาน กรณีเพิ่มประเภทอาหาร หรือ เปลี่ยนแปลงแบบแปลนแผนผัง หรือเปลี่ยนแปลงเครื่องจักร (แบบ สบ.2) [ตามบัญชี 1 ข้อ 1.1(2.1)]', '500');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (3, 1, 'ค่าพิจารณาการยื่นแบบการแก้ไขสถานที่ผลิตอาหารที่ไม่เข้าข่ายโรงงาน กรณีแก้ไขรายการอื่น นอกเหนือจากการเพิ่มประเภทหรือเปลี่ยนแปลงแบบแปลนแผนผังหรือเครื่องจักร (แบบ สบ.2) [ตามบัญชี 1 ข้อ 1.1(2.2)]', '250');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (4, 1, 'ค่าพิจารณาคำขออนุญาตตั้งโรงงานผลิตอาหาร (แบบ อ.1) [ตามบัญชี 1 ข้อ 1.1(3)]', '2000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (5, 1, 'ค่าพิจารณาคำขอต่ออายุใบอนุญาตผลิตอาหาร (แบบ อ.3) [ตามบัญชี 1 ข้อ 1.1(4)]', '500');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (6, 1, 'ค่าพิจารณาคำขออนุญาตย้ายสถานที่ผลิตหรือสถานที่เก็บอาหาร (แบบ อ.5) กรณีย้ายสถานที่ผลิตและสถานที่เก็บอาหาร [ตามบัญชี 1 ข้อ 1.1(5.1)]', '2000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (7, 1, 'ค่าตรวจสถานประกอบการด้านอาหาร - กรณีใช้เครื่องจักรที่มีกำลังรวมไม่เกิน 5 แรงม้า และคนงาน 1-6 คน [ตามบัญชี 2 ข้อ 2.5(1)]', '3000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (8, 1, 'ค่าตรวจสถานประกอบการอาหาร กรณีใช้เครื่องจักรที่มีกำลังรวมมากกว่า 5 แรงม้าแต่ไม่เกิน 20 แรงม้า หรือคนงาน 7-50 คน [ตามบัญชี 2 ข้อ 2.5(2)]', '5000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (9, 1, 'ค่าตรวจสถานประกอบการอาหาร กรณีใช้เครื่องจักรที่มีกำลังรวมมากกว่า 20 แรงม้าแต่ไม่เกิน 50 แรงม้า หรือคนงาน 51-100 คน [ตามบัญชี 2 ข้อ 2.5(3)]', '10000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (10, 1, 'ค่าบริการตรวจสอบและบันทึกข้อมูลการยื่นคำขอในระบบ E-submission (เฉพาะผู้ประสงค์จะให้เจ้าหน้าที่บันทึกข้อมูลแทน) กรณีที่ไม่ต้องแจ้งสูตรส่วนประกอบและไม่ต้องแนบเอกสาร [ตามบัญชี 3 ข้อ 3.1(5.1)]', '200');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (11, 1, 'ค่าบริการตรวจสอบและบันทึกข้อมูลการยื่นคำขอในระบบ E-submission (เฉพาะผู้ประสงค์จะให้เจ้าหน้าที่บันทึกข้อมูลแทน) กรณีที่ต้องแจ้งสูตรส่วนประกอบหรือต้องแนบเอกสาร [ตามบัญชี 3 ข้อ 3.1(5.2)]', '500');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (12, 1, 'ค่าวินิจฉัยประเภทอาหาร โดยตอบเป็นหนังสือ [ตามบัญชี 3 ข้อ 3.1(3.1)]', '1000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (13, 1, 'ค่าพิจารณาใบรับรองสถานที่ผลิตอาหารในต่างประเทศ หรือค่าพิจารณาเทียบมาตรฐานสถานที่ผลิตของต่างประเทศ โดยตอบเป็นหนังสือ [ตามบัญชี 3 ข้อ 3.1(3.1)]', '1000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (14, 1, 'ค่าพิจารณาสูตร หรือฉลากอาหาร โดยตอบเป็นหนังสือ [ตามบัญชี 3 ข้อ 3.1(3.1)]', '1000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (15, 1, 'ค่าพิจารณาแบบแปลนแผนผัง และกรรมวิธีการผลิต ที่มีความซับซ้อน [ตามบัญชี 3 ข้อ 3.1(3.2)]', '3000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (16, 1, 'ค่าพิจารณา วินิจฉัย รับรอง ขอความเห็นชอบ ตอบข้อหารือ บริการข้อมูล โดยตอบเป็นหนังสือ กรณีเรื่องยาก ซับซ้อน อื่นๆ [ตามบัญชี 3 ข้อ 3.1(3.2)]', '3000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (17, 1, 'ค่าใบอนุญาตโฆษณาอาหาร [ตามบัญชี 3 ข้อ 3.2(1)]', '5000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (18, 1, 'ค่าใบอนุญาตโฆษณาอาหาร [ตามบัญชี 3 ข้อ 3.2(1)] (ส่วนลดกรณีอ้างอิงการโฆษณาอาหารที่ได้รับอนุญาตเดิมและไม่มีการแก้ไขเพิ่มเติมการโฆษณาอาหารอาหารที่นำมาอ้างอิง)', '660');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (19, 1, 'ค่าใบแทนใบอนุญาตโฆษณา [ตามบัญชี 3 ข้อ 3.2(2)]', '500');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (20, 2, 'ใบอนุญาตผลิตอาหารสำหรับโรงงานที่ประกอบกิจการ โดยใช้คนงาน 7-19 คน โดยไม่ใช้เครื่องจักร หรือใช้เครื่องจักรที่มีกำลังรวมไม่ถึง 5 แรงม้า', '3000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (21, 2, 'ใบอนุญาตผลิตอาหารสำหรับโรงงานที่ประกอบกิจการ โดยใช้คนงาน ตั้งแต่ 20 คนขึ้นไป โดยไม่ใช้เครื่องจักร หรือใช้เครื่องจักรที่มีกำลังรวมไม่ถึง 5 แรงม้า', '5000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (22, 2, 'ใบอนุญาตผลิตอาหารสำหรับโรงงานที่ประกอบกิจการโดยใช้เครื่องจักรตั้งแต่ 5 แรงม้า หรือกำลังเทียบเท่าตั้งแต่ 5 แรงม้า แต่ไม่ถึง 10 แรงม้า', '6000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (23, 2, 'ใบอนุญาตผลิตอาหารสำหรับโรงงานที่ประกอบกิจการโดยใช้เครื่องจักรที่มีกำลังรวมตั้งแต่ 10 แรงม้า หรือกำลังเทียบเท่าตั้งแต่ 10 แรงม้า แต่ไม่ถึง 25 แรงม้า', '7000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (24, 2, 'ใบอนุญาตผลิตอาหารสำหรับโรงงานที่ประกอบกิจการโดยใช้เครื่องจักรที่มีกำลังรวมตั้งแต่ 25 แรงม้า หรือกำลังเทียบเท่าตั้งแต่ 25 แรงม้า แต่ไม่ถึง 50 แรงม้า', '8000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (25, 4, 'ใบอนุญาตผลิตยาแผนปัจจุบัน ฉบับละ 8,000 บาท', '8000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (26, 4, 'ใบอนุญาตขายยาแผนปัจจุบัน', '2000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (27, 3, 'ตรวจ GPP สถานที่ขายยา', '2000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (28, 3, 'ตรวจ GMP สถานที่ผลิตยาแผนโบราณตามภาคผนวก ข และภาคผนวก ค', '5000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (29, 3, 'ตรวจ GMP สถานที่ผลิตยาแผนปัจจุบัน', '50000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (30, 4, 'ใบแทนใบสาคัญการขึ้นทะเบียนตำรับยาแผนโบราณ', '100');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (31, 5, 'คำขอรับใบอนุญาตขายวัตถุออกฤทธิ์ประเภท 3  หรือ ประเภท 4', '500');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (32, 5, 'คำขอต่ออายุใบอนุญาตวัตถุออกฤทธิ์ทุกประเภท', '300');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (33, 5, 'คำขอแก้ไขรายการในใบอนุญาตวัตถุออกฤทธิ์ทุกประเภท', '300');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (34, 6, 'ใบอนุญาตขายวัตถุออกฤทธิ์ในประเภท 2  ประเภท 3  หรือ ประเภท 4', '1000');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (35, 6, 'ใบอนุญาตให้มีไว้ในครอบครองหรือใช้ประโยชน์วัตถุออกฤทธิ์', '500');
INSERT INTO "ListFees"("id_list", "id_type", "description", "price") VALUES (36, 6, 'ใบแทนใบอนุญาตด้านวัตถุออกฤทธิ์', '100');
